### ISSUE TITLE
Crash at Gson adapter

### ISSUE THREAD

**Issue by Null45** [alexbbb/android-host-monitor#8]
```
Fatal Exception: java.lang.AssertionError: Missing field in net.gotev.hostmonitor.a
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.(SourceFile)
       at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:838)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(SourceFile:135)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.(SourceFile)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:104)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:160)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:96)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.internal.bind.MapTypeAdapterFactory.create(SourceFile:126)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.Gson.fromJson(SourceFile:878)
       at com.google.gson.Gson.fromJson(SourceFile:844)
       at com.google.gson.Gson.fromJson(SourceFile:793)
       at net.gotev.hostmonitor.HostMonitorConfig.getHostsMap(SourceFile:74)
       at net.gotev.hostmonitor.HostMonitor.onHandleIntent(SourceFile:83)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.lang.NoSuchFieldException: NONE
       at java.lang.Class.getField(Class.java:724)
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.(SourceFile)
       at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:838)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(SourceFile:135)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.(SourceFile)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:104)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:160)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:96)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.internal.bind.MapTypeAdapterFactory.create(SourceFile:126)
       at com.google.gson.Gson.getAdapter(SourceFile:416)
       at com.google.gson.Gson.fromJson(SourceFile:878)
       at com.google.gson.Gson.fromJson(SourceFile:844)
       at com.google.gson.Gson.fromJson(SourceFile:793)
       at net.gotev.hostmonitor.HostMonitorConfig.getHostsMap(SourceFile:74)
       at net.gotev.hostmonitor.HostMonitor.onHandleIntent(SourceFile:83)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
Strange crash, how to fix it? Tried to add -keep class net.gotev.* in my proguard rules, but not hepled

**Comment by gotev** [comment]
Never experienced that. Try to disable proguard and see if it happens again. Have you added also exceptions for Gson?

**Comment by Null45** [comment]
Which exceptions?

**Comment by gotev** [comment]
The gson rules for proguard

**Comment by Null45** [comment]
```
        try {
            new HostMonitorConfig(this)
                    .setBroadcastAction(BuildConfig.APPLICATION_ID)
                    .add(ApiHelper.API_ADDRESS, 80)
                    .save();
        } catch (Throwable e) {}
```

Added this, but not helps

**Comment by gotev** [comment]
Disable ProGuard. Catching exceptions in those cases is useless.
